include_guard(GLOBAL)

set(LICOSIM_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB LICOSIM_SOURCES
	${LICOSIM_DIR}/src/*.hpp
	${LICOSIM_DIR}/src/*.cpp)

include("${LICOSIM_DIR}/src/rxtools/RxTools.cmake")

set(LICOSIM_EXTERNAL_INCLUDES
	${RXTOOLS_INCLUDES}
	)

set(LICOSIM_EXTERNAL_LINKS
	${RXTOOLS_LINKS}
	)

set(LICOSIM_INCLUDES
	${LICOSIM_EXTERNAL_INCLUDES}
	${LICOSIM_DIR}/src
	)
set(LICOSIM_LINKS
	${LICOSIM_EXTERNAL_LINKS}
	licosim
	)
